version: '3.1'
services:
  app:
    container_name: my-chat-backend
    image: my-chat-backend
    build: ./
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbpostgresql:5432/postgres
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=pawelr
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres